// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy/message.proto

package message

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListPoliciesRequest_Type int32

const (
	ListPoliciesRequest_ALL              ListPoliciesRequest_Type = 0
	ListPoliciesRequest_SYSTEM           ListPoliciesRequest_Type = 1
	ListPoliciesRequest_CUSTOMER_DEFINED ListPoliciesRequest_Type = 2
	ListPoliciesRequest_PRE_DEFIEND      ListPoliciesRequest_Type = 3
	ListPoliciesRequest_TRIAL            ListPoliciesRequest_Type = 4
)

var ListPoliciesRequest_Type_name = map[int32]string{
	0: "ALL",
	1: "SYSTEM",
	2: "CUSTOMER_DEFINED",
	3: "PRE_DEFIEND",
	4: "TRIAL",
}

var ListPoliciesRequest_Type_value = map[string]int32{
	"ALL":              0,
	"SYSTEM":           1,
	"CUSTOMER_DEFINED": 2,
	"PRE_DEFIEND":      3,
	"TRIAL":            4,
}

func (x ListPoliciesRequest_Type) String() string {
	return proto.EnumName(ListPoliciesRequest_Type_name, int32(x))
}

func (ListPoliciesRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{6, 0}
}

type ListUserRequest_TypeData int32

const (
	ListUserRequest_ALL              ListUserRequest_TypeData = 0
	ListUserRequest_SYSTEM           ListUserRequest_TypeData = 1
	ListUserRequest_CUSTOMER_DEFINED ListUserRequest_TypeData = 2
	ListUserRequest_PRE_DEFIEND      ListUserRequest_TypeData = 3
	ListUserRequest_TRIAL            ListUserRequest_TypeData = 4
)

var ListUserRequest_TypeData_name = map[int32]string{
	0: "ALL",
	1: "SYSTEM",
	2: "CUSTOMER_DEFINED",
	3: "PRE_DEFIEND",
	4: "TRIAL",
}

var ListUserRequest_TypeData_value = map[string]int32{
	"ALL":              0,
	"SYSTEM":           1,
	"CUSTOMER_DEFINED": 2,
	"PRE_DEFIEND":      3,
	"TRIAL":            4,
}

func (x ListUserRequest_TypeData) String() string {
	return proto.EnumName(ListUserRequest_TypeData_name, int32(x))
}

func (ListUserRequest_TypeData) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{24, 0}
}

type ListGroupRequest_TypeData int32

const (
	ListGroupRequest_ALL              ListGroupRequest_TypeData = 0
	ListGroupRequest_SYSTEM           ListGroupRequest_TypeData = 1
	ListGroupRequest_CUSTOMER_DEFINED ListGroupRequest_TypeData = 2
	ListGroupRequest_PRE_DEFIEND      ListGroupRequest_TypeData = 3
	ListGroupRequest_TRIAL            ListGroupRequest_TypeData = 4
)

var ListGroupRequest_TypeData_name = map[int32]string{
	0: "ALL",
	1: "SYSTEM",
	2: "CUSTOMER_DEFINED",
	3: "PRE_DEFIEND",
	4: "TRIAL",
}

var ListGroupRequest_TypeData_value = map[string]int32{
	"ALL":              0,
	"SYSTEM":           1,
	"CUSTOMER_DEFINED": 2,
	"PRE_DEFIEND":      3,
	"TRIAL":            4,
}

func (x ListGroupRequest_TypeData) String() string {
	return proto.EnumName(ListGroupRequest_TypeData_name, int32(x))
}

func (ListGroupRequest_TypeData) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{33, 0}
}

type PolicyIdRequest struct {
	PolicyId             string   `protobuf:"bytes,1,opt,name=PolicyId,proto3" json:"PolicyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyIdRequest) Reset()         { *m = PolicyIdRequest{} }
func (m *PolicyIdRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyIdRequest) ProtoMessage()    {}
func (*PolicyIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{0}
}

func (m *PolicyIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyIdRequest.Unmarshal(m, b)
}
func (m *PolicyIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyIdRequest.Marshal(b, m, deterministic)
}
func (m *PolicyIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyIdRequest.Merge(m, src)
}
func (m *PolicyIdRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyIdRequest.Size(m)
}
func (m *PolicyIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyIdRequest proto.InternalMessageInfo

func (m *PolicyIdRequest) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

type UpdateInfoRequest struct {
	PolicyId             string           `protobuf:"bytes,1,opt,name=PolicyId,proto3" json:"PolicyId,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	ResourceTypes        []*ResourceTypes `protobuf:"bytes,4,rep,name=ResourceTypes,proto3" json:"ResourceTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{1}
}

func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(m, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *UpdateInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateInfoRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateInfoRequest) GetResourceTypes() []*ResourceTypes {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

type PolicyNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyNameRequest) Reset()         { *m = PolicyNameRequest{} }
func (m *PolicyNameRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyNameRequest) ProtoMessage()    {}
func (*PolicyNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{2}
}

func (m *PolicyNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyNameRequest.Unmarshal(m, b)
}
func (m *PolicyNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyNameRequest.Marshal(b, m, deterministic)
}
func (m *PolicyNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyNameRequest.Merge(m, src)
}
func (m *PolicyNameRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyNameRequest.Size(m)
}
func (m *PolicyNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyNameRequest proto.InternalMessageInfo

func (m *PolicyNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdRequest) Reset()         { *m = UserIdRequest{} }
func (m *UserIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserIdRequest) ProtoMessage()    {}
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{3}
}

func (m *UserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdRequest.Unmarshal(m, b)
}
func (m *UserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdRequest.Marshal(b, m, deterministic)
}
func (m *UserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdRequest.Merge(m, src)
}
func (m *UserIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserIdRequest.Size(m)
}
func (m *UserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdRequest proto.InternalMessageInfo

func (m *UserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// Policy data from database
type PolicyData struct {
	// PolicyID represent policy_id
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Customer number
	CustomerNumber string `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	// Policy's name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Policy's description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Policy's version
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Policy's type
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Policy's Activation status
	IsActive bool `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Policy's resource types
	ResourceTypes        []*ResourceTypes `protobuf:"bytes,8,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PolicyData) Reset()         { *m = PolicyData{} }
func (m *PolicyData) String() string { return proto.CompactTextString(m) }
func (*PolicyData) ProtoMessage()    {}
func (*PolicyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{4}
}

func (m *PolicyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyData.Unmarshal(m, b)
}
func (m *PolicyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyData.Marshal(b, m, deterministic)
}
func (m *PolicyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyData.Merge(m, src)
}
func (m *PolicyData) XXX_Size() int {
	return xxx_messageInfo_PolicyData.Size(m)
}
func (m *PolicyData) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyData.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyData proto.InternalMessageInfo

func (m *PolicyData) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *PolicyData) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *PolicyData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PolicyData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PolicyData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PolicyData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PolicyData) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *PolicyData) GetResourceTypes() []*ResourceTypes {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

// Policy's resource type message
type ResourceTypes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Effect               string   `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	Actions              []string `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Resources            []string `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceTypes) Reset()         { *m = ResourceTypes{} }
func (m *ResourceTypes) String() string { return proto.CompactTextString(m) }
func (*ResourceTypes) ProtoMessage()    {}
func (*ResourceTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{5}
}

func (m *ResourceTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTypes.Unmarshal(m, b)
}
func (m *ResourceTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTypes.Marshal(b, m, deterministic)
}
func (m *ResourceTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTypes.Merge(m, src)
}
func (m *ResourceTypes) XXX_Size() int {
	return xxx_messageInfo_ResourceTypes.Size(m)
}
func (m *ResourceTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTypes proto.InternalMessageInfo

func (m *ResourceTypes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceTypes) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *ResourceTypes) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ResourceTypes) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ListPoliciesRequest struct {
	// Limit response data, limit gt 5
	Limit uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Skip to a position, skip gt 0
	Skip uint64 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// Keyword (optional)
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Default by created_at
	Keysort string `protobuf:"bytes,7,opt,name=keysort,proto3" json:"keysort,omitempty"`
	// Set data response ascending
	IsAsc bool `protobuf:"varint,4,opt,name=is_asc,json=isAsc,proto3" json:"is_asc,omitempty"`
	// Get active data only
	IsActive string `protobuf:"bytes,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Get policy type
	Type                 ListPoliciesRequest_Type `protobuf:"varint,6,opt,name=type,proto3,enum=ListPoliciesRequest_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListPoliciesRequest) Reset()         { *m = ListPoliciesRequest{} }
func (m *ListPoliciesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPoliciesRequest) ProtoMessage()    {}
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{6}
}

func (m *ListPoliciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoliciesRequest.Unmarshal(m, b)
}
func (m *ListPoliciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoliciesRequest.Marshal(b, m, deterministic)
}
func (m *ListPoliciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoliciesRequest.Merge(m, src)
}
func (m *ListPoliciesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPoliciesRequest.Size(m)
}
func (m *ListPoliciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoliciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoliciesRequest proto.InternalMessageInfo

func (m *ListPoliciesRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPoliciesRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListPoliciesRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *ListPoliciesRequest) GetKeysort() string {
	if m != nil {
		return m.Keysort
	}
	return ""
}

func (m *ListPoliciesRequest) GetIsAsc() bool {
	if m != nil {
		return m.IsAsc
	}
	return false
}

func (m *ListPoliciesRequest) GetIsActive() string {
	if m != nil {
		return m.IsActive
	}
	return ""
}

func (m *ListPoliciesRequest) GetType() ListPoliciesRequest_Type {
	if m != nil {
		return m.Type
	}
	return ListPoliciesRequest_ALL
}

type PoliciesResponse struct {
	// Total policy queried
	TotalItems int64 `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	// List of all Policy data
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PoliciesResponse) Reset()         { *m = PoliciesResponse{} }
func (m *PoliciesResponse) String() string { return proto.CompactTextString(m) }
func (*PoliciesResponse) ProtoMessage()    {}
func (*PoliciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{7}
}

func (m *PoliciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoliciesResponse.Unmarshal(m, b)
}
func (m *PoliciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoliciesResponse.Marshal(b, m, deterministic)
}
func (m *PoliciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoliciesResponse.Merge(m, src)
}
func (m *PoliciesResponse) XXX_Size() int {
	return xxx_messageInfo_PoliciesResponse.Size(m)
}
func (m *PoliciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PoliciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PoliciesResponse proto.InternalMessageInfo

func (m *PoliciesResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *PoliciesResponse) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{8}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{9}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetByResourceRequest struct {
	// Resource types name
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// Resource type orn (policies ID)
	ResourceOrn string `protobuf:"bytes,2,opt,name=resource_orn,json=resourceOrn,proto3" json:"resource_orn,omitempty"`
	// Resource type effect
	Effect               string   `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByResourceRequest) Reset()         { *m = GetByResourceRequest{} }
func (m *GetByResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetByResourceRequest) ProtoMessage()    {}
func (*GetByResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{10}
}

func (m *GetByResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByResourceRequest.Unmarshal(m, b)
}
func (m *GetByResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetByResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByResourceRequest.Merge(m, src)
}
func (m *GetByResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetByResourceRequest.Size(m)
}
func (m *GetByResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByResourceRequest proto.InternalMessageInfo

func (m *GetByResourceRequest) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *GetByResourceRequest) GetResourceOrn() string {
	if m != nil {
		return m.ResourceOrn
	}
	return ""
}

func (m *GetByResourceRequest) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type GetByResourceData struct {
	PolicyId             string           `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ResourceTypes        []*ResourceTypes `protobuf:"bytes,4,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	Users                []string         `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetByResourceData) Reset()         { *m = GetByResourceData{} }
func (m *GetByResourceData) String() string { return proto.CompactTextString(m) }
func (*GetByResourceData) ProtoMessage()    {}
func (*GetByResourceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{11}
}

func (m *GetByResourceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByResourceData.Unmarshal(m, b)
}
func (m *GetByResourceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByResourceData.Marshal(b, m, deterministic)
}
func (m *GetByResourceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByResourceData.Merge(m, src)
}
func (m *GetByResourceData) XXX_Size() int {
	return xxx_messageInfo_GetByResourceData.Size(m)
}
func (m *GetByResourceData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByResourceData.DiscardUnknown(m)
}

var xxx_messageInfo_GetByResourceData proto.InternalMessageInfo

func (m *GetByResourceData) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *GetByResourceData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetByResourceData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetByResourceData) GetResourceTypes() []*ResourceTypes {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

func (m *GetByResourceData) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetByResourceResponse struct {
	Data                 []*GetByResourceData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetByResourceResponse) Reset()         { *m = GetByResourceResponse{} }
func (m *GetByResourceResponse) String() string { return proto.CompactTextString(m) }
func (*GetByResourceResponse) ProtoMessage()    {}
func (*GetByResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{12}
}

func (m *GetByResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByResourceResponse.Unmarshal(m, b)
}
func (m *GetByResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByResourceResponse.Marshal(b, m, deterministic)
}
func (m *GetByResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByResourceResponse.Merge(m, src)
}
func (m *GetByResourceResponse) XXX_Size() int {
	return xxx_messageInfo_GetByResourceResponse.Size(m)
}
func (m *GetByResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByResourceResponse proto.InternalMessageInfo

func (m *GetByResourceResponse) GetData() []*GetByResourceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetByGroupRequest struct {
	// GroupIDs requested
	GroupIds             string   `protobuf:"bytes,1,opt,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByGroupRequest) Reset()         { *m = GetByGroupRequest{} }
func (m *GetByGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetByGroupRequest) ProtoMessage()    {}
func (*GetByGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{13}
}

func (m *GetByGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByGroupRequest.Unmarshal(m, b)
}
func (m *GetByGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetByGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByGroupRequest.Merge(m, src)
}
func (m *GetByGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetByGroupRequest.Size(m)
}
func (m *GetByGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByGroupRequest proto.InternalMessageInfo

func (m *GetByGroupRequest) GetGroupIds() string {
	if m != nil {
		return m.GroupIds
	}
	return ""
}

type GetByGroupResponse struct {
	// Total policy queried
	TotalItems int64 `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	// List of all Policy data
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetByGroupResponse) Reset()         { *m = GetByGroupResponse{} }
func (m *GetByGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetByGroupResponse) ProtoMessage()    {}
func (*GetByGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{14}
}

func (m *GetByGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByGroupResponse.Unmarshal(m, b)
}
func (m *GetByGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetByGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByGroupResponse.Merge(m, src)
}
func (m *GetByGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetByGroupResponse.Size(m)
}
func (m *GetByGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByGroupResponse proto.InternalMessageInfo

func (m *GetByGroupResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *GetByGroupResponse) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreatePolicyData struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ResourceTypes        []*ResourceTypes `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreatePolicyData) Reset()         { *m = CreatePolicyData{} }
func (m *CreatePolicyData) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyData) ProtoMessage()    {}
func (*CreatePolicyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{15}
}

func (m *CreatePolicyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyData.Unmarshal(m, b)
}
func (m *CreatePolicyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyData.Marshal(b, m, deterministic)
}
func (m *CreatePolicyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyData.Merge(m, src)
}
func (m *CreatePolicyData) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyData.Size(m)
}
func (m *CreatePolicyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyData proto.InternalMessageInfo

func (m *CreatePolicyData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePolicyData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePolicyData) GetResourceTypes() []*ResourceTypes {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

type CreatePolicyRequest struct {
	UserId               string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body                 *CreatePolicyData `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreatePolicyRequest) Reset()         { *m = CreatePolicyRequest{} }
func (m *CreatePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyRequest) ProtoMessage()    {}
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{16}
}

func (m *CreatePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyRequest.Unmarshal(m, b)
}
func (m *CreatePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyRequest.Marshal(b, m, deterministic)
}
func (m *CreatePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyRequest.Merge(m, src)
}
func (m *CreatePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyRequest.Size(m)
}
func (m *CreatePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyRequest proto.InternalMessageInfo

func (m *CreatePolicyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePolicyRequest) GetBody() *CreatePolicyData {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreatePolicyResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyResponse) Reset()         { *m = CreatePolicyResponse{} }
func (m *CreatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyResponse) ProtoMessage()    {}
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{17}
}

func (m *CreatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyResponse.Unmarshal(m, b)
}
func (m *CreatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyResponse.Marshal(b, m, deterministic)
}
func (m *CreatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyResponse.Merge(m, src)
}
func (m *CreatePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyResponse.Size(m)
}
func (m *CreatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyResponse proto.InternalMessageInfo

func (m *CreatePolicyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreatePolicyResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeletePolicyRequest struct {
	PolicyIds            string   `protobuf:"bytes,1,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyRequest) Reset()         { *m = DeletePolicyRequest{} }
func (m *DeletePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyRequest) ProtoMessage()    {}
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{18}
}

func (m *DeletePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyRequest.Unmarshal(m, b)
}
func (m *DeletePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyRequest.Marshal(b, m, deterministic)
}
func (m *DeletePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyRequest.Merge(m, src)
}
func (m *DeletePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyRequest.Size(m)
}
func (m *DeletePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyRequest proto.InternalMessageInfo

func (m *DeletePolicyRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

type DeletePolicyResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyResponse) Reset()         { *m = DeletePolicyResponse{} }
func (m *DeletePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyResponse) ProtoMessage()    {}
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{19}
}

func (m *DeletePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyResponse.Unmarshal(m, b)
}
func (m *DeletePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyResponse.Marshal(b, m, deterministic)
}
func (m *DeletePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyResponse.Merge(m, src)
}
func (m *DeletePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyResponse.Size(m)
}
func (m *DeletePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyResponse proto.InternalMessageInfo

func (m *DeletePolicyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeletePolicyResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AttachPolicyRequest struct {
	// Request list policy ids
	PolicyIds string `protobuf:"bytes,1,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	// Group Id to attach
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachPolicyRequest) Reset()         { *m = AttachPolicyRequest{} }
func (m *AttachPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*AttachPolicyRequest) ProtoMessage()    {}
func (*AttachPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{20}
}

func (m *AttachPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachPolicyRequest.Unmarshal(m, b)
}
func (m *AttachPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachPolicyRequest.Marshal(b, m, deterministic)
}
func (m *AttachPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachPolicyRequest.Merge(m, src)
}
func (m *AttachPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_AttachPolicyRequest.Size(m)
}
func (m *AttachPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachPolicyRequest proto.InternalMessageInfo

func (m *AttachPolicyRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

func (m *AttachPolicyRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type DetachPolicyRequest struct {
	// Request list policy ids
	PolicyIds string `protobuf:"bytes,1,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	// Group Id to attach
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachPolicyRequest) Reset()         { *m = DetachPolicyRequest{} }
func (m *DetachPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*DetachPolicyRequest) ProtoMessage()    {}
func (*DetachPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{21}
}

func (m *DetachPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachPolicyRequest.Unmarshal(m, b)
}
func (m *DetachPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachPolicyRequest.Marshal(b, m, deterministic)
}
func (m *DetachPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachPolicyRequest.Merge(m, src)
}
func (m *DetachPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_DetachPolicyRequest.Size(m)
}
func (m *DetachPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetachPolicyRequest proto.InternalMessageInfo

func (m *DetachPolicyRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

func (m *DetachPolicyRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type AttachPolicyToUserRequest struct {
	// Request list policy ids
	PolicyIds string `protobuf:"bytes,1,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	// User Id to attach
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachPolicyToUserRequest) Reset()         { *m = AttachPolicyToUserRequest{} }
func (m *AttachPolicyToUserRequest) String() string { return proto.CompactTextString(m) }
func (*AttachPolicyToUserRequest) ProtoMessage()    {}
func (*AttachPolicyToUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{22}
}

func (m *AttachPolicyToUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachPolicyToUserRequest.Unmarshal(m, b)
}
func (m *AttachPolicyToUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachPolicyToUserRequest.Marshal(b, m, deterministic)
}
func (m *AttachPolicyToUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachPolicyToUserRequest.Merge(m, src)
}
func (m *AttachPolicyToUserRequest) XXX_Size() int {
	return xxx_messageInfo_AttachPolicyToUserRequest.Size(m)
}
func (m *AttachPolicyToUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachPolicyToUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachPolicyToUserRequest proto.InternalMessageInfo

func (m *AttachPolicyToUserRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

func (m *AttachPolicyToUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DetachPolicyFromUserRequest struct {
	// Request list policy ids
	PolicyIds string `protobuf:"bytes,1,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	// User Id to detach
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachPolicyFromUserRequest) Reset()         { *m = DetachPolicyFromUserRequest{} }
func (m *DetachPolicyFromUserRequest) String() string { return proto.CompactTextString(m) }
func (*DetachPolicyFromUserRequest) ProtoMessage()    {}
func (*DetachPolicyFromUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{23}
}

func (m *DetachPolicyFromUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachPolicyFromUserRequest.Unmarshal(m, b)
}
func (m *DetachPolicyFromUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachPolicyFromUserRequest.Marshal(b, m, deterministic)
}
func (m *DetachPolicyFromUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachPolicyFromUserRequest.Merge(m, src)
}
func (m *DetachPolicyFromUserRequest) XXX_Size() int {
	return xxx_messageInfo_DetachPolicyFromUserRequest.Size(m)
}
func (m *DetachPolicyFromUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachPolicyFromUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetachPolicyFromUserRequest proto.InternalMessageInfo

func (m *DetachPolicyFromUserRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

func (m *DetachPolicyFromUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListUserRequest struct {
	// Limit response data, limit gt 5
	Limit uint64 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Skip to a position, skip gt 0
	Skip uint64 `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	// Keyword (optional)
	Keyword string `protobuf:"bytes,3,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	// Default by created_at
	Keysort string `protobuf:"bytes,4,opt,name=Keysort,proto3" json:"Keysort,omitempty"`
	// Set data response ascending
	IsAsc bool `protobuf:"varint,5,opt,name=IsAsc,proto3" json:"IsAsc,omitempty"`
	// Get active data only
	IsActive string `protobuf:"bytes,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	// Get policy type
	Type                 ListUserRequest_TypeData `protobuf:"varint,7,opt,name=Type,proto3,enum=ListUserRequest_TypeData" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{24}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUserRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListUserRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *ListUserRequest) GetKeysort() string {
	if m != nil {
		return m.Keysort
	}
	return ""
}

func (m *ListUserRequest) GetIsAsc() bool {
	if m != nil {
		return m.IsAsc
	}
	return false
}

func (m *ListUserRequest) GetIsActive() string {
	if m != nil {
		return m.IsActive
	}
	return ""
}

func (m *ListUserRequest) GetType() ListUserRequest_TypeData {
	if m != nil {
		return m.Type
	}
	return ListUserRequest_ALL
}

type ListUsersResponse struct {
	// Total user queried
	TotalItems int64 `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	// List of all user data
	Data                 []*UserData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{25}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *ListUsersResponse) GetData() []*UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BindSystemPolicyRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindSystemPolicyRequest) Reset()         { *m = BindSystemPolicyRequest{} }
func (m *BindSystemPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*BindSystemPolicyRequest) ProtoMessage()    {}
func (*BindSystemPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{26}
}

func (m *BindSystemPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindSystemPolicyRequest.Unmarshal(m, b)
}
func (m *BindSystemPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindSystemPolicyRequest.Marshal(b, m, deterministic)
}
func (m *BindSystemPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindSystemPolicyRequest.Merge(m, src)
}
func (m *BindSystemPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_BindSystemPolicyRequest.Size(m)
}
func (m *BindSystemPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindSystemPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindSystemPolicyRequest proto.InternalMessageInfo

func (m *BindSystemPolicyRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type BindResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindResponse) Reset()         { *m = BindResponse{} }
func (m *BindResponse) String() string { return proto.CompactTextString(m) }
func (*BindResponse) ProtoMessage()    {}
func (*BindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{27}
}

func (m *BindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindResponse.Unmarshal(m, b)
}
func (m *BindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindResponse.Marshal(b, m, deterministic)
}
func (m *BindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindResponse.Merge(m, src)
}
func (m *BindResponse) XXX_Size() int {
	return xxx_messageInfo_BindResponse.Size(m)
}
func (m *BindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindResponse proto.InternalMessageInfo

func (m *BindResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type BindUserPolicyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PolicyIds            string   `protobuf:"bytes,2,opt,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindUserPolicyRequest) Reset()         { *m = BindUserPolicyRequest{} }
func (m *BindUserPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*BindUserPolicyRequest) ProtoMessage()    {}
func (*BindUserPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{28}
}

func (m *BindUserPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindUserPolicyRequest.Unmarshal(m, b)
}
func (m *BindUserPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindUserPolicyRequest.Marshal(b, m, deterministic)
}
func (m *BindUserPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindUserPolicyRequest.Merge(m, src)
}
func (m *BindUserPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_BindUserPolicyRequest.Size(m)
}
func (m *BindUserPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindUserPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindUserPolicyRequest proto.InternalMessageInfo

func (m *BindUserPolicyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BindUserPolicyRequest) GetPolicyIds() string {
	if m != nil {
		return m.PolicyIds
	}
	return ""
}

type GetSystemPoliciesRequest struct {
	// Limit response data, limit gt 5
	Limit uint64 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Skip to a position, skip gt 0
	Skip uint64 `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	// Keyword (optional)
	Keyword string `protobuf:"bytes,3,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	// Default by created_at
	Keysort string `protobuf:"bytes,4,opt,name=Keysort,proto3" json:"Keysort,omitempty"`
	// Set data response ascending
	IsAsc bool `protobuf:"varint,5,opt,name=IsAsc,proto3" json:"IsAsc,omitempty"`
	// Get active data only
	IsActive             bool     `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemPoliciesRequest) Reset()         { *m = GetSystemPoliciesRequest{} }
func (m *GetSystemPoliciesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemPoliciesRequest) ProtoMessage()    {}
func (*GetSystemPoliciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{29}
}

func (m *GetSystemPoliciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemPoliciesRequest.Unmarshal(m, b)
}
func (m *GetSystemPoliciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemPoliciesRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemPoliciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemPoliciesRequest.Merge(m, src)
}
func (m *GetSystemPoliciesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemPoliciesRequest.Size(m)
}
func (m *GetSystemPoliciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemPoliciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemPoliciesRequest proto.InternalMessageInfo

func (m *GetSystemPoliciesRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetSystemPoliciesRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetSystemPoliciesRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *GetSystemPoliciesRequest) GetKeysort() string {
	if m != nil {
		return m.Keysort
	}
	return ""
}

func (m *GetSystemPoliciesRequest) GetIsAsc() bool {
	if m != nil {
		return m.IsAsc
	}
	return false
}

func (m *GetSystemPoliciesRequest) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type GetSystemPoliciesResponse struct {
	TotalItems           int64         `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSystemPoliciesResponse) Reset()         { *m = GetSystemPoliciesResponse{} }
func (m *GetSystemPoliciesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSystemPoliciesResponse) ProtoMessage()    {}
func (*GetSystemPoliciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{30}
}

func (m *GetSystemPoliciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemPoliciesResponse.Unmarshal(m, b)
}
func (m *GetSystemPoliciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemPoliciesResponse.Marshal(b, m, deterministic)
}
func (m *GetSystemPoliciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemPoliciesResponse.Merge(m, src)
}
func (m *GetSystemPoliciesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSystemPoliciesResponse.Size(m)
}
func (m *GetSystemPoliciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemPoliciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemPoliciesResponse proto.InternalMessageInfo

func (m *GetSystemPoliciesResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *GetSystemPoliciesResponse) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetSystemPoliciesByUserIdResponse struct {
	TotalItems           int64              `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	Data                 []*CachePolicyData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetSystemPoliciesByUserIdResponse) Reset()         { *m = GetSystemPoliciesByUserIdResponse{} }
func (m *GetSystemPoliciesByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetSystemPoliciesByUserIdResponse) ProtoMessage()    {}
func (*GetSystemPoliciesByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{31}
}

func (m *GetSystemPoliciesByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemPoliciesByUserIdResponse.Unmarshal(m, b)
}
func (m *GetSystemPoliciesByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemPoliciesByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetSystemPoliciesByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemPoliciesByUserIdResponse.Merge(m, src)
}
func (m *GetSystemPoliciesByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetSystemPoliciesByUserIdResponse.Size(m)
}
func (m *GetSystemPoliciesByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemPoliciesByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemPoliciesByUserIdResponse proto.InternalMessageInfo

func (m *GetSystemPoliciesByUserIdResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *GetSystemPoliciesByUserIdResponse) GetData() []*CachePolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CachePolicyData struct {
	PolicyId             string           `protobuf:"bytes,1,opt,name=PolicyId,proto3" json:"PolicyId,omitempty"`
	ResourceTypes        []*ResourceTypes `protobuf:"bytes,2,rep,name=ResourceTypes,proto3" json:"ResourceTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CachePolicyData) Reset()         { *m = CachePolicyData{} }
func (m *CachePolicyData) String() string { return proto.CompactTextString(m) }
func (*CachePolicyData) ProtoMessage()    {}
func (*CachePolicyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{32}
}

func (m *CachePolicyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachePolicyData.Unmarshal(m, b)
}
func (m *CachePolicyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachePolicyData.Marshal(b, m, deterministic)
}
func (m *CachePolicyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachePolicyData.Merge(m, src)
}
func (m *CachePolicyData) XXX_Size() int {
	return xxx_messageInfo_CachePolicyData.Size(m)
}
func (m *CachePolicyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CachePolicyData.DiscardUnknown(m)
}

var xxx_messageInfo_CachePolicyData proto.InternalMessageInfo

func (m *CachePolicyData) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *CachePolicyData) GetResourceTypes() []*ResourceTypes {
	if m != nil {
		return m.ResourceTypes
	}
	return nil
}

type ListGroupRequest struct {
	// Limit response data, limit gt 5
	Limit uint64 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Skip to a position, skip gt 0
	Skip uint64 `protobuf:"varint,2,opt,name=Skip,proto3" json:"Skip,omitempty"`
	// Keyword (optional)
	Keyword string `protobuf:"bytes,3,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	// Default by created_at
	Keysort string `protobuf:"bytes,4,opt,name=Keysort,proto3" json:"Keysort,omitempty"`
	// Set data response ascending
	IsAsc bool `protobuf:"varint,5,opt,name=IsAsc,proto3" json:"IsAsc,omitempty"`
	// Get active data only
	IsActive string `protobuf:"bytes,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	// Get policy type
	Type                 ListGroupRequest_TypeData `protobuf:"varint,7,opt,name=Type,proto3,enum=ListGroupRequest_TypeData" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListGroupRequest) Reset()         { *m = ListGroupRequest{} }
func (m *ListGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupRequest) ProtoMessage()    {}
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{33}
}

func (m *ListGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupRequest.Unmarshal(m, b)
}
func (m *ListGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupRequest.Merge(m, src)
}
func (m *ListGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupRequest.Size(m)
}
func (m *ListGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupRequest proto.InternalMessageInfo

func (m *ListGroupRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListGroupRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListGroupRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *ListGroupRequest) GetKeysort() string {
	if m != nil {
		return m.Keysort
	}
	return ""
}

func (m *ListGroupRequest) GetIsAsc() bool {
	if m != nil {
		return m.IsAsc
	}
	return false
}

func (m *ListGroupRequest) GetIsActive() string {
	if m != nil {
		return m.IsActive
	}
	return ""
}

func (m *ListGroupRequest) GetType() ListGroupRequest_TypeData {
	if m != nil {
		return m.Type
	}
	return ListGroupRequest_ALL
}

type ListGroupResponse struct {
	// Total group queried
	TotalItems int64 `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	// List of all Group data
	Data                 []*GroupData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListGroupResponse) Reset()         { *m = ListGroupResponse{} }
func (m *ListGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupResponse) ProtoMessage()    {}
func (*ListGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{34}
}

func (m *ListGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupResponse.Unmarshal(m, b)
}
func (m *ListGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupResponse.Merge(m, src)
}
func (m *ListGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupResponse.Size(m)
}
func (m *ListGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupResponse proto.InternalMessageInfo

func (m *ListGroupResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *ListGroupResponse) GetData() []*GroupData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GroupData struct {
	GroupId              string        `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GroupData) Reset()         { *m = GroupData{} }
func (m *GroupData) String() string { return proto.CompactTextString(m) }
func (*GroupData) ProtoMessage()    {}
func (*GroupData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{35}
}

func (m *GroupData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupData.Unmarshal(m, b)
}
func (m *GroupData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupData.Marshal(b, m, deterministic)
}
func (m *GroupData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupData.Merge(m, src)
}
func (m *GroupData) XXX_Size() int {
	return xxx_messageInfo_GroupData.Size(m)
}
func (m *GroupData) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupData.DiscardUnknown(m)
}

var xxx_messageInfo_GroupData proto.InternalMessageInfo

func (m *GroupData) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupData) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GroupIdRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupIdRequest) Reset()         { *m = GroupIdRequest{} }
func (m *GroupIdRequest) String() string { return proto.CompactTextString(m) }
func (*GroupIdRequest) ProtoMessage()    {}
func (*GroupIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{36}
}

func (m *GroupIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupIdRequest.Unmarshal(m, b)
}
func (m *GroupIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupIdRequest.Marshal(b, m, deterministic)
}
func (m *GroupIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupIdRequest.Merge(m, src)
}
func (m *GroupIdRequest) XXX_Size() int {
	return xxx_messageInfo_GroupIdRequest.Size(m)
}
func (m *GroupIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupIdRequest proto.InternalMessageInfo

func (m *GroupIdRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type ListUserResponse struct {
	// Total users queried
	TotalItems int64 `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	// List of all users data
	Data                 []*UserData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{37}
}

func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (m *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(m, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *ListUserResponse) GetData() []*UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserData struct {
	UserId               string        `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{38}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserData) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListPoliciesResponse struct {
	TotalItems           int64         `protobuf:"varint,1,opt,name=TotalItems,proto3" json:"TotalItems,omitempty"`
	Data                 []*PolicyData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPoliciesResponse) Reset()         { *m = ListPoliciesResponse{} }
func (m *ListPoliciesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPoliciesResponse) ProtoMessage()    {}
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d32c77b7dbbaef1b, []int{39}
}

func (m *ListPoliciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoliciesResponse.Unmarshal(m, b)
}
func (m *ListPoliciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoliciesResponse.Marshal(b, m, deterministic)
}
func (m *ListPoliciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoliciesResponse.Merge(m, src)
}
func (m *ListPoliciesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPoliciesResponse.Size(m)
}
func (m *ListPoliciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoliciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoliciesResponse proto.InternalMessageInfo

func (m *ListPoliciesResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *ListPoliciesResponse) GetData() []*PolicyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("ListPoliciesRequest_Type", ListPoliciesRequest_Type_name, ListPoliciesRequest_Type_value)
	proto.RegisterEnum("ListUserRequest_TypeData", ListUserRequest_TypeData_name, ListUserRequest_TypeData_value)
	proto.RegisterEnum("ListGroupRequest_TypeData", ListGroupRequest_TypeData_name, ListGroupRequest_TypeData_value)
	proto.RegisterType((*PolicyIdRequest)(nil), "PolicyIdRequest")
	proto.RegisterType((*UpdateInfoRequest)(nil), "UpdateInfoRequest")
	proto.RegisterType((*PolicyNameRequest)(nil), "PolicyNameRequest")
	proto.RegisterType((*UserIdRequest)(nil), "UserIdRequest")
	proto.RegisterType((*PolicyData)(nil), "PolicyData")
	proto.RegisterType((*ResourceTypes)(nil), "ResourceTypes")
	proto.RegisterType((*ListPoliciesRequest)(nil), "ListPoliciesRequest")
	proto.RegisterType((*PoliciesResponse)(nil), "PoliciesResponse")
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*GetByResourceRequest)(nil), "GetByResourceRequest")
	proto.RegisterType((*GetByResourceData)(nil), "GetByResourceData")
	proto.RegisterType((*GetByResourceResponse)(nil), "GetByResourceResponse")
	proto.RegisterType((*GetByGroupRequest)(nil), "GetByGroupRequest")
	proto.RegisterType((*GetByGroupResponse)(nil), "GetByGroupResponse")
	proto.RegisterType((*CreatePolicyData)(nil), "CreatePolicyData")
	proto.RegisterType((*CreatePolicyRequest)(nil), "CreatePolicyRequest")
	proto.RegisterType((*CreatePolicyResponse)(nil), "CreatePolicyResponse")
	proto.RegisterType((*DeletePolicyRequest)(nil), "DeletePolicyRequest")
	proto.RegisterType((*DeletePolicyResponse)(nil), "DeletePolicyResponse")
	proto.RegisterType((*AttachPolicyRequest)(nil), "AttachPolicyRequest")
	proto.RegisterType((*DetachPolicyRequest)(nil), "DetachPolicyRequest")
	proto.RegisterType((*AttachPolicyToUserRequest)(nil), "AttachPolicyToUserRequest")
	proto.RegisterType((*DetachPolicyFromUserRequest)(nil), "DetachPolicyFromUserRequest")
	proto.RegisterType((*ListUserRequest)(nil), "ListUserRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "ListUsersResponse")
	proto.RegisterType((*BindSystemPolicyRequest)(nil), "BindSystemPolicyRequest")
	proto.RegisterType((*BindResponse)(nil), "BindResponse")
	proto.RegisterType((*BindUserPolicyRequest)(nil), "BindUserPolicyRequest")
	proto.RegisterType((*GetSystemPoliciesRequest)(nil), "GetSystemPoliciesRequest")
	proto.RegisterType((*GetSystemPoliciesResponse)(nil), "GetSystemPoliciesResponse")
	proto.RegisterType((*GetSystemPoliciesByUserIdResponse)(nil), "GetSystemPoliciesByUserIdResponse")
	proto.RegisterType((*CachePolicyData)(nil), "CachePolicyData")
	proto.RegisterType((*ListGroupRequest)(nil), "ListGroupRequest")
	proto.RegisterType((*ListGroupResponse)(nil), "ListGroupResponse")
	proto.RegisterType((*GroupData)(nil), "GroupData")
	proto.RegisterType((*GroupIdRequest)(nil), "GroupIdRequest")
	proto.RegisterType((*ListUserResponse)(nil), "ListUserResponse")
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*ListPoliciesResponse)(nil), "ListPoliciesResponse")
}

func init() { proto.RegisterFile("policy/message.proto", fileDescriptor_d32c77b7dbbaef1b) }

var fileDescriptor_d32c77b7dbbaef1b = []byte{
	// 1930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x59, 0xcd, 0x73, 0x1b, 0x49,
	0x15, 0xf7, 0x48, 0x23, 0x69, 0xf4, 0x6c, 0x59, 0xe3, 0xf6, 0x97, 0xa2, 0xfd, 0x8a, 0x87, 0xad,
	0x25, 0x45, 0x91, 0x76, 0xac, 0x0d, 0x64, 0xb3, 0x81, 0x80, 0x15, 0x29, 0x41, 0xc4, 0xf9, 0x60,
	0xec, 0x40, 0x2d, 0x1f, 0xa5, 0x92, 0xa5, 0xb1, 0x77, 0x58, 0x49, 0x23, 0x66, 0x46, 0xd9, 0x12,
	0x47, 0x8e, 0x7b, 0xe4, 0xca, 0x89, 0x03, 0x37, 0x0e, 0x54, 0x71, 0xe1, 0x3f, 0xe0, 0xc6, 0x8d,
	0xbf, 0x81, 0xe2, 0xc4, 0xdd, 0x27, 0xba, 0x7b, 0xba, 0x35, 0xdd, 0x33, 0xa3, 0xb5, 0xbc, 0x98,
	0x14, 0xc5, 0xc5, 0xa5, 0x79, 0xdd, 0xef, 0xfb, 0xd7, 0xef, 0xbd, 0x6e, 0xc3, 0xd6, 0xc4, 0x1b,
	0xba, 0xfd, 0xd9, 0xfe, 0xc8, 0x09, 0x82, 0xde, 0xb9, 0x83, 0x27, 0xbe, 0x17, 0x7a, 0xf5, 0xdb,
	0xe7, 0x6e, 0xf8, 0xe9, 0xf4, 0x14, 0xf7, 0xbd, 0xd1, 0xfe, 0xc8, 0xed, 0xfb, 0xde, 0xfe, 0xb9,
	0x77, 0x3b, 0xfa, 0xd1, 0x9b, 0xb8, 0xfb, 0x6c, 0x13, 0xfd, 0xc5, 0xb7, 0xef, 0xbe, 0xee, 0x0d,
	0xdd, 0x41, 0x2f, 0x74, 0xf6, 0xc5, 0x8f, 0x68, 0xc1, 0xba, 0x07, 0xd5, 0x97, 0x4c, 0x7e, 0x67,
	0x60, 0x3b, 0xbf, 0x9a, 0x3a, 0x41, 0x88, 0xde, 0x07, 0x43, 0x90, 0x6a, 0xda, 0x4d, 0xed, 0x56,
	0xb9, 0x69, 0x5c, 0x34, 0x0b, 0x7e, 0xfe, 0x4f, 0x9a, 0x66, 0xcf, 0x57, 0xac, 0xbf, 0x68, 0xb0,
	0xf1, 0x6a, 0x42, 0x25, 0x75, 0xc6, 0x67, 0xde, 0x95, 0x78, 0xd1, 0x5b, 0xa0, 0x3f, 0xef, 0x8d,
	0x9c, 0x5a, 0x8e, 0xed, 0x28, 0x5d, 0x34, 0x75, 0x3f, 0xf7, 0xd3, 0x15, 0x9b, 0x11, 0xd1, 0x4d,
	0x58, 0x6d, 0x39, 0x41, 0xdf, 0x77, 0x27, 0xa1, 0xeb, 0x8d, 0x6b, 0x79, 0xba, 0xc7, 0x96, 0x49,
	0xe8, 0x21, 0x54, 0x6c, 0x27, 0xf0, 0xa6, 0x7e, 0xdf, 0x39, 0x99, 0x4d, 0x9c, 0xa0, 0xa6, 0xdf,
	0xcc, 0xdf, 0x5a, 0x6d, 0xac, 0x63, 0x85, 0xca, 0x34, 0xff, 0x56, 0xcb, 0x19, 0x9a, 0xad, 0x6e,
	0xb7, 0xee, 0xc0, 0x46, 0x64, 0x0a, 0xd5, 0x27, 0x2c, 0x17, 0x36, 0x69, 0x19, 0x36, 0x59, 0x07,
	0x50, 0x79, 0x15, 0x38, 0x7e, 0x1c, 0xa3, 0x9b, 0x50, 0x8c, 0x08, 0x29, 0x2f, 0x39, 0xdd, 0xfa,
	0x22, 0x07, 0x10, 0x69, 0x69, 0xf5, 0xc2, 0x1e, 0x11, 0x5f, 0x8e, 0xf2, 0xd8, 0x75, 0x39, 0x8f,
	0x6d, 0x4c, 0x44, 0x3c, 0xbe, 0x0e, 0xd5, 0xfe, 0x34, 0x08, 0xbd, 0x91, 0xe3, 0x77, 0xc7, 0xd3,
	0xd1, 0xa9, 0xe3, 0x47, 0xa1, 0xb1, 0xd7, 0x05, 0xf9, 0x39, 0xa3, 0x22, 0x04, 0xfa, 0x98, 0x1a,
	0x19, 0x05, 0x85, 0xfd, 0xa6, 0xf1, 0x1a, 0x48, 0xf1, 0xd2, 0xa3, 0x78, 0x49, 0x24, 0x54, 0x83,
	0xd2, 0x6b, 0xc7, 0x0f, 0xe8, 0x6a, 0x81, 0xad, 0x8a, 0x4f, 0x2a, 0x2f, 0x24, 0x21, 0xa9, 0x15,
	0x23, 0x79, 0xf4, 0x37, 0xb5, 0xd4, 0x0d, 0xba, 0xbd, 0x7e, 0xe8, 0xbe, 0x76, 0x6a, 0x25, 0xb2,
	0x60, 0xd8, 0x86, 0x1b, 0x1c, 0xb2, 0x6f, 0xf4, 0x2d, 0x58, 0xf7, 0x79, 0x2c, 0xbb, 0x21, 0x8b,
	0xbd, 0x91, 0x15, 0x7b, 0xbb, 0xe2, 0x2b, 0x11, 0xff, 0x9d, 0x96, 0x48, 0xd9, 0xdc, 0x13, 0x4d,
	0xf2, 0xe4, 0x1b, 0x50, 0x74, 0xce, 0xce, 0x9c, 0x7e, 0xc8, 0x81, 0x81, 0x2e, 0x9a, 0x55, 0xbf,
	0x62, 0x17, 0x7a, 0xc3, 0xa1, 0xf7, 0xb9, 0xad, 0x0f, 0x9c, 0xf1, 0xcc, 0xe6, 0x3b, 0x90, 0x05,
	0x25, 0x6a, 0xa2, 0x37, 0x0e, 0x48, 0x30, 0xf2, 0x3c, 0x03, 0x51, 0xb6, 0xc5, 0x02, 0xfa, 0x00,
	0xca, 0xc2, 0x8c, 0x08, 0x23, 0xf2, 0xae, 0x78, 0xc9, 0xfa, 0x67, 0x0e, 0x36, 0x8f, 0xdc, 0x20,
	0x64, 0xe9, 0x72, 0x89, 0xf5, 0x3c, 0xc9, 0xef, 0x40, 0x61, 0xe8, 0x8e, 0xdc, 0x90, 0x19, 0xa9,
	0x33, 0x4c, 0x34, 0x72, 0xb7, 0x0a, 0x76, 0x44, 0xa5, 0x88, 0x09, 0x3e, 0x73, 0x27, 0xcc, 0xd8,
	0xf9, 0x2a, 0x41, 0x0c, 0x25, 0xa2, 0x3d, 0x28, 0x7d, 0xe6, 0xcc, 0x3e, 0xf7, 0xfc, 0x41, 0x94,
	0x2c, 0x8e, 0xa8, 0x5b, 0x55, 0x5b, 0xd0, 0xf9, 0x96, 0xc0, 0xf3, 0x43, 0x16, 0xe6, 0xc4, 0x16,
	0x4a, 0x47, 0xdb, 0x50, 0xa4, 0xb9, 0x08, 0xfa, 0x2c, 0xad, 0x86, 0x5d, 0x20, 0x89, 0x08, 0xfa,
	0xe8, 0x40, 0x4e, 0x11, 0x4b, 0x69, 0x73, 0xeb, 0xa2, 0xb9, 0xe1, 0x57, 0x49, 0x0a, 0xfd, 0xa9,
	0x63, 0x17, 0xce, 0x7a, 0xc3, 0xc0, 0xb1, 0x57, 0xa4, 0xc4, 0xdd, 0x93, 0x32, 0xbd, 0xde, 0xb8,
	0x81, 0x33, 0xfc, 0xc5, 0x34, 0x33, 0x2c, 0x42, 0xbf, 0xd1, 0x72, 0xa6, 0x16, 0xc1, 0xc1, 0x7a,
	0x06, 0x3a, 0xa5, 0xa3, 0x12, 0xe4, 0x0f, 0x8f, 0x8e, 0xcc, 0x15, 0x04, 0x50, 0x3c, 0xfe, 0xe4,
	0xf8, 0xa4, 0xfd, 0xcc, 0xd4, 0xd0, 0x16, 0x98, 0x8f, 0x5e, 0x1d, 0x9f, 0xbc, 0x78, 0xd6, 0xb6,
	0xbb, 0xad, 0xf6, 0xe3, 0xce, 0xf3, 0x76, 0xcb, 0xcc, 0xa1, 0x2a, 0xac, 0xbe, 0xb4, 0xdb, 0x8c,
	0xd0, 0x7e, 0xde, 0x32, 0xf3, 0xa8, 0x0c, 0x85, 0x13, 0xbb, 0x73, 0x78, 0x64, 0xea, 0xd6, 0x09,
	0x98, 0xb1, 0xda, 0x60, 0x42, 0xd2, 0xe4, 0xa0, 0xf7, 0x60, 0x35, 0xf4, 0xc2, 0xde, 0xb0, 0xeb,
	0x86, 0xce, 0x28, 0x60, 0xd1, 0xce, 0xdb, 0xc0, 0x48, 0x1d, 0x4a, 0x21, 0x1b, 0x74, 0x52, 0x68,
	0x7a, 0x24, 0xd2, 0x14, 0x6b, 0xab, 0x38, 0x3e, 0x57, 0x36, 0x5b, 0xb0, 0x2c, 0x58, 0xfb, 0x81,
	0x43, 0x50, 0x22, 0x32, 0x97, 0x81, 0x2e, 0x6b, 0x0f, 0x2a, 0x7c, 0x0f, 0x57, 0x6b, 0x42, 0x7e,
	0x14, 0x9c, 0xf3, 0x3d, 0xf4, 0xa7, 0xf5, 0x47, 0x0d, 0xb6, 0x9e, 0x38, 0x61, 0x73, 0x26, 0xb0,
	0x2a, 0xe4, 0xdd, 0x85, 0x8a, 0x02, 0x7b, 0x7e, 0xea, 0xab, 0x17, 0xcd, 0x35, 0x1f, 0x1a, 0xc6,
	0xcf, 0xee, 0xdc, 0xbe, 0xdf, 0xbb, 0xfd, 0xeb, 0x5f, 0xd8, 0x6b, 0x32, 0xec, 0x51, 0x03, 0xe6,
	0xdf, 0x5d, 0xcf, 0x1f, 0x73, 0x54, 0xa7, 0x98, 0x56, 0xc5, 0xa6, 0x17, 0xfe, 0x58, 0x3a, 0x03,
	0xf9, 0xcb, 0xce, 0x80, 0xf5, 0x67, 0x52, 0x82, 0x15, 0x73, 0x2f, 0xaf, 0x34, 0x22, 0x30, 0xb9,
	0xc5, 0x05, 0x24, 0x9f, 0x2e, 0x20, 0xe9, 0x53, 0xaf, 0x2f, 0x71, 0xea, 0x09, 0x3a, 0x0a, 0x53,
	0x52, 0x0c, 0x03, 0x02, 0x51, 0x72, 0xf6, 0xec, 0xe8, 0xc3, 0xfa, 0x1e, 0x6c, 0x27, 0x62, 0xcc,
	0xf3, 0xf1, 0x01, 0xcf, 0xb2, 0xc6, 0x64, 0x23, 0x9c, 0x72, 0x8d, 0x27, 0xfb, 0x90, 0x7b, 0xfd,
	0xc4, 0xf7, 0xa6, 0x13, 0x91, 0xa1, 0x6f, 0x42, 0xf9, 0x9c, 0x7e, 0x13, 0xa7, 0x83, 0x45, 0xd9,
	0x31, 0xd8, 0x8e, 0xce, 0x20, 0xb0, 0x7e, 0x0c, 0x48, 0x16, 0x71, 0x6d, 0x38, 0xfc, 0xbd, 0x46,
	0x0e, 0x84, 0xef, 0x90, 0xa6, 0x28, 0x95, 0xfe, 0xaf, 0xc9, 0x60, 0x4c, 0x5b, 0x15, 0x25, 0xe1,
	0x40, 0x4d, 0xc2, 0x22, 0xa8, 0x7c, 0x79, 0x56, 0xf2, 0xcb, 0xd4, 0xe2, 0x2e, 0x6c, 0xca, 0x26,
	0x8a, 0x00, 0xee, 0x42, 0x89, 0xe6, 0x27, 0x06, 0x4d, 0x71, 0xca, 0x1a, 0x19, 0xda, 0x07, 0xfd,
	0xd4, 0x1b, 0xcc, 0x98, 0x49, 0xab, 0x8d, 0x0d, 0x9c, 0xf4, 0x8f, 0x55, 0x8c, 0x2f, 0xa2, 0x8a,
	0x41, 0x37, 0x5a, 0x4d, 0xd8, 0x52, 0x15, 0xf0, 0xf0, 0x92, 0x36, 0x14, 0x4c, 0xfb, 0xa4, 0xe0,
	0x46, 0xa1, 0x35, 0x6c, 0xf1, 0x29, 0x4e, 0x62, 0x2e, 0x3e, 0x89, 0x6d, 0xd8, 0x6c, 0x39, 0x43,
	0x27, 0x69, 0x24, 0x06, 0x98, 0x63, 0x7b, 0x61, 0x9a, 0xcb, 0x02, 0xed, 0x01, 0x35, 0x45, 0x15,
	0xf3, 0x15, 0x4c, 0xf9, 0x25, 0x6c, 0x1e, 0x86, 0x61, 0xaf, 0xff, 0xe9, 0x7f, 0x64, 0x0a, 0x41,
	0x81, 0x21, 0x00, 0xca, 0xb3, 0x1b, 0xcf, 0x0c, 0x25, 0x0e, 0x4c, 0xaa, 0xab, 0xe5, 0xbc, 0x21,
	0x5d, 0x63, 0xb8, 0x21, 0xfb, 0x75, 0xe2, 0xd1, 0xc1, 0xe5, 0xab, 0x6a, 0xdc, 0x8b, 0xd1, 0x93,
	0x54, 0xc8, 0x71, 0x64, 0x4d, 0xe0, 0x2d, 0xd9, 0xb7, 0xc7, 0xbe, 0x37, 0xfa, 0x2f, 0x6b, 0xfc,
	0x47, 0x0e, 0xaa, 0xb4, 0xcf, 0xc9, 0x6a, 0x48, 0x4f, 0x3f, 0xca, 0xec, 0xe9, 0x47, 0xa2, 0xa7,
	0x1f, 0x67, 0xf5, 0xf4, 0x63, 0xde, 0xd3, 0x9f, 0x2e, 0xe8, 0xe9, 0x4f, 0xe3, 0x9e, 0xfe, 0x94,
	0xf7, 0x74, 0x3d, 0xbd, 0x85, 0xf5, 0x74, 0x52, 0x15, 0x3b, 0xb4, 0x8b, 0xb3, 0xc6, 0x4d, 0x5a,
	0x3a, 0xfb, 0x40, 0x77, 0xc0, 0xe8, 0xf0, 0x5e, 0x1d, 0x4d, 0x63, 0x8b, 0x3a, 0x7a, 0x47, 0xea,
	0xe8, 0xf4, 0x40, 0xb3, 0xd9, 0x41, 0x74, 0x74, 0xc9, 0x53, 0xd6, 0xcd, 0xe7, 0xe7, 0x93, 0x77,
	0x74, 0x4a, 0xb3, 0x7e, 0x04, 0x86, 0x58, 0xbb, 0xae, 0xae, 0x6e, 0xc3, 0x86, 0x50, 0x1f, 0xb7,
	0xf5, 0x77, 0x01, 0x4e, 0xe6, 0xb5, 0x53, 0x54, 0xd3, 0x98, 0x42, 0x52, 0xa1, 0xb7, 0xe2, 0x6a,
	0x5a, 0xc6, 0x94, 0x3b, 0xaa, 0xa5, 0xf4, 0x2f, 0xb9, 0x99, 0xec, 0x36, 0xdd, 0xf1, 0xe0, 0x78,
	0x16, 0x90, 0xdd, 0xea, 0x79, 0x78, 0x1b, 0xf4, 0xe9, 0xd4, 0x4d, 0xcf, 0xde, 0x8c, 0x4a, 0x87,
	0x01, 0xca, 0x38, 0xb7, 0x83, 0xf4, 0xbc, 0xbe, 0x37, 0x70, 0xb8, 0x05, 0xec, 0xb7, 0xf5, 0x09,
	0x6c, 0xd3, 0x3d, 0x54, 0xa5, 0x2a, 0x7a, 0x2f, 0x51, 0x06, 0xd3, 0xb0, 0x22, 0x76, 0xcb, 0x48,
	0x8d, 0x2a, 0x85, 0x54, 0x73, 0xfe, 0xa6, 0x41, 0x8d, 0x34, 0x17, 0xc9, 0x6e, 0x75, 0xa4, 0xfc,
	0x9f, 0x84, 0x5f, 0x3d, 0x01, 0x3f, 0x23, 0x06, 0x9a, 0xf5, 0x73, 0xb8, 0x91, 0xe1, 0xcf, 0x92,
	0x49, 0x7e, 0x4f, 0x49, 0xb2, 0xda, 0x32, 0x59, 0x9a, 0x5d, 0xd8, 0x4b, 0x49, 0x6f, 0xce, 0xc4,
	0x6d, 0x6b, 0x49, 0x2d, 0xef, 0x2b, 0x5a, 0x4c, 0xfc, 0x88, 0x94, 0x19, 0x27, 0xa5, 0xaa, 0x0f,
	0xd5, 0xc4, 0x02, 0xf5, 0x5b, 0xbd, 0xaf, 0x4a, 0xb7, 0xd4, 0xbb, 0xc9, 0x6b, 0x66, 0x2e, 0xbb,
	0xbd, 0xaa, 0x97, 0x4b, 0x72, 0x99, 0x30, 0xe9, 0x59, 0x50, 0xa6, 0x93, 0xff, 0x9f, 0xaa, 0xf3,
	0x91, 0x52, 0x75, 0xea, 0x38, 0xe9, 0xea, 0x1b, 0x2d, 0x3b, 0xc7, 0x51, 0xd9, 0x51, 0xa7, 0xb8,
	0xcb, 0xb0, 0xf2, 0xae, 0x82, 0x15, 0xc0, 0x8c, 0x5b, 0x42, 0xc9, 0x63, 0x28, 0xcf, 0x49, 0x74,
	0x50, 0x78, 0x12, 0xf5, 0x4b, 0x0e, 0x0f, 0xf1, 0x79, 0x39, 0xb0, 0xef, 0xc2, 0x3a, 0xdf, 0x2b,
	0x50, 0x60, 0x25, 0x84, 0xc9, 0x5d, 0x99, 0x2f, 0x90, 0x28, 0x99, 0x71, 0x21, 0xbf, 0x9e, 0x42,
	0xfa, 0x08, 0x0c, 0x41, 0x41, 0x3b, 0xea, 0xbb, 0x85, 0x78, 0xad, 0xb8, 0xdc, 0x9b, 0x9f, 0xc0,
	0x96, 0x7a, 0x65, 0xbc, 0xa6, 0xf3, 0xdf, 0xf8, 0x97, 0x4e, 0xb0, 0x30, 0x71, 0xc9, 0x69, 0xab,
	0xca, 0x0a, 0x0e, 0x5f, 0x76, 0x50, 0x15, 0x9f, 0x7b, 0x98, 0xbe, 0x61, 0xf1, 0x00, 0xd6, 0xcd,
	0x98, 0xc0, 0xd5, 0x7f, 0x48, 0x82, 0x4c, 0x07, 0xf9, 0x48, 0xec, 0x92, 0x4c, 0x07, 0xb0, 0xc6,
	0x98, 0xa8, 0xef, 0x4b, 0xb2, 0x34, 0xa0, 0x12, 0x5f, 0x18, 0x96, 0xe4, 0x21, 0x1e, 0xc9, 0x73,
	0xf0, 0xf2, 0x5c, 0xd1, 0xb3, 0xda, 0x55, 0xb9, 0xe4, 0x41, 0x77, 0x49, 0xae, 0x07, 0xb0, 0xa3,
	0x8e, 0x80, 0x57, 0x71, 0xef, 0xbb, 0x50, 0x4b, 0xce, 0x73, 0x57, 0x61, 0xff, 0x18, 0xb6, 0xd3,
	0xe3, 0xe7, 0x92, 0xbc, 0xdf, 0x81, 0xdd, 0xac, 0x51, 0x72, 0x39, 0xee, 0xc6, 0xdf, 0x73, 0xa4,
	0xe8, 0xb0, 0x7e, 0x43, 0x02, 0x60, 0x26, 0x67, 0x0c, 0x54, 0xc3, 0x0b, 0xc6, 0x8e, 0x7a, 0x05,
	0x2b, 0x73, 0xc5, 0x3d, 0x58, 0x57, 0x67, 0x08, 0xb4, 0x83, 0x33, 0x87, 0x8a, 0x24, 0xe3, 0x0f,
	0xd9, 0x05, 0x56, 0x6d, 0x79, 0xe8, 0x06, 0x5e, 0x34, 0x34, 0xd4, 0xeb, 0x78, 0x71, 0xff, 0x7d,
	0x91, 0xd1, 0x9c, 0x45, 0xfb, 0x44, 0xeb, 0x58, 0x79, 0xb5, 0xac, 0x5b, 0xf8, 0xf2, 0x56, 0xfb,
	0x11, 0xbb, 0x9e, 0xcb, 0xee, 0x37, 0xd9, 0x3b, 0x29, 0x42, 0x38, 0xf5, 0x68, 0x5a, 0x97, 0xcf,
	0x73, 0xe3, 0xaf, 0x1a, 0x14, 0x18, 0x02, 0xc8, 0xcd, 0x14, 0xe6, 0x75, 0x39, 0x40, 0x1b, 0xa9,
	0x26, 0x51, 0x47, 0x38, 0x55, 0xb7, 0xad, 0x15, 0xd4, 0x86, 0x77, 0x22, 0xe8, 0xcf, 0x67, 0x49,
	0xd6, 0xae, 0xf9, 0xa9, 0x23, 0xfe, 0x54, 0xb1, 0x5a, 0x51, 0xeb, 0x1b, 0x38, 0x59, 0x2c, 0x89,
	0x98, 0xef, 0xc3, 0x4e, 0x24, 0x86, 0xd2, 0x99, 0x84, 0xce, 0x38, 0xb2, 0x2b, 0xc5, 0xbf, 0x8d,
	0xb3, 0x8a, 0x5a, 0xe3, 0x01, 0xe8, 0x94, 0x97, 0x54, 0x97, 0xf2, 0xdc, 0x14, 0x64, 0x26, 0x27,
	0x6c, 0xee, 0x85, 0x32, 0xf4, 0x5a, 0x2b, 0x8d, 0x3f, 0x14, 0xa1, 0xc8, 0xf1, 0x70, 0x1f, 0xd6,
	0x64, 0xf9, 0x68, 0x2b, 0xeb, 0xd9, 0x8d, 0x38, 0x91, 0x34, 0x80, 0x38, 0xf1, 0x31, 0x94, 0xc5,
	0x5c, 0x11, 0xa0, 0x6d, 0x9c, 0xf5, 0x2a, 0x55, 0xdf, 0xc1, 0xd9, 0x0f, 0x29, 0x07, 0x50, 0xe4,
	0xa1, 0xe7, 0x8f, 0x28, 0x4a, 0xec, 0x37, 0x71, 0xc6, 0xd3, 0xc7, 0x43, 0xd8, 0x25, 0x54, 0xd9,
	0xba, 0x85, 0x20, 0xca, 0x34, 0x97, 0xd4, 0x1f, 0xc2, 0x7f, 0x25, 0xbc, 0x10, 0xae, 0x07, 0xb0,
	0x26, 0x57, 0x48, 0x12, 0x9f, 0x8c, 0x97, 0x09, 0x92, 0xa4, 0xcc, 0xe7, 0x84, 0x6f, 0xc3, 0xa6,
	0xa4, 0x72, 0x3e, 0xb5, 0x99, 0x38, 0xf1, 0xff, 0x8c, 0xa4, 0xd2, 0xfb, 0x02, 0x1e, 0x29, 0x56,
	0x84, 0x53, 0xff, 0xd0, 0x50, 0x98, 0xa9, 0xbd, 0x72, 0x95, 0x25, 0xf6, 0x66, 0x3c, 0x52, 0x10,
	0x7b, 0x33, 0xdf, 0x1c, 0x1e, 0xaa, 0xef, 0x08, 0xbc, 0xd8, 0x12, 0x19, 0x19, 0xaf, 0x0b, 0x19,
	0x41, 0x26, 0xb0, 0xde, 0xce, 0xac, 0xb7, 0xcc, 0x8a, 0xa5, 0x24, 0x3c, 0x02, 0x94, 0x2e, 0xb9,
	0xa8, 0x8e, 0x17, 0x3e, 0x03, 0x64, 0x09, 0x79, 0x42, 0x9f, 0x54, 0xd2, 0xb5, 0x17, 0xbd, 0x8d,
	0xbf, 0xe4, 0x76, 0x9f, 0x21, 0xe8, 0xb4, 0xc8, 0xfe, 0x01, 0xf5, 0xe1, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0x6f, 0x9b, 0x19, 0xe0, 0x1a, 0x00, 0x00,
}
