// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type ThingRequest struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingRequest) Reset()         { *m = ThingRequest{} }
func (m *ThingRequest) String() string { return proto.CompactTextString(m) }
func (*ThingRequest) ProtoMessage()    {}
func (*ThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{1}
}

func (m *ThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingRequest.Unmarshal(m, b)
}
func (m *ThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingRequest.Marshal(b, m, deterministic)
}
func (m *ThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingRequest.Merge(m, src)
}
func (m *ThingRequest) XXX_Size() int {
	return xxx_messageInfo_ThingRequest.Size(m)
}
func (m *ThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThingRequest proto.InternalMessageInfo

func (m *ThingRequest) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

type ThingResponse struct {
	DisplayName          string              `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Serial               string              `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Properties           []*PropertyResponse `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	Name                 string              `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Template             *Template           `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ThingResponse) Reset()         { *m = ThingResponse{} }
func (m *ThingResponse) String() string { return proto.CompactTextString(m) }
func (*ThingResponse) ProtoMessage()    {}
func (*ThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{2}
}

func (m *ThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingResponse.Unmarshal(m, b)
}
func (m *ThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingResponse.Marshal(b, m, deterministic)
}
func (m *ThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingResponse.Merge(m, src)
}
func (m *ThingResponse) XXX_Size() int {
	return xxx_messageInfo_ThingResponse.Size(m)
}
func (m *ThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ThingResponse proto.InternalMessageInfo

func (m *ThingResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ThingResponse) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *ThingResponse) GetProperties() []*PropertyResponse {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ThingResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThingResponse) GetTemplate() *Template {
	if m != nil {
		return m.Template
	}
	return nil
}

type PropertyResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyResponse) Reset()         { *m = PropertyResponse{} }
func (m *PropertyResponse) String() string { return proto.CompactTextString(m) }
func (*PropertyResponse) ProtoMessage()    {}
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{3}
}

func (m *PropertyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyResponse.Unmarshal(m, b)
}
func (m *PropertyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyResponse.Marshal(b, m, deterministic)
}
func (m *PropertyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyResponse.Merge(m, src)
}
func (m *PropertyResponse) XXX_Size() int {
	return xxx_messageInfo_PropertyResponse.Size(m)
}
func (m *PropertyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyResponse proto.InternalMessageInfo

func (m *PropertyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PropertyResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Template struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{4}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DataRequest struct {
	CustomerNumber       string       `protobuf:"bytes,1,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	ThingName            string       `protobuf:"bytes,2,opt,name=thingName,proto3" json:"thingName,omitempty"`
	ThingDisplayName     string       `protobuf:"bytes,3,opt,name=thingDisplayName,proto3" json:"thingDisplayName,omitempty"`
	ThingSerial          string       `protobuf:"bytes,4,opt,name=thingSerial,proto3" json:"thingSerial,omitempty"`
	PropertyName         string       `protobuf:"bytes,5,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
	DataType             int32        `protobuf:"varint,6,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Value                string       `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	PropertyId           int32        `protobuf:"varint,8,opt,name=propertyId,proto3" json:"propertyId,omitempty"`
	ThingId              int32        `protobuf:"varint,9,opt,name=thingId,proto3" json:"thingId,omitempty"`
	Alerts               []*AlertData `protobuf:"bytes,10,rep,name=alerts,proto3" json:"alerts,omitempty"`
	TemplateId           int32        `protobuf:"varint,11,opt,name=templateId,proto3" json:"templateId,omitempty"`
	TemplateName         string       `protobuf:"bytes,12,opt,name=templateName,proto3" json:"templateName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{5}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetCustomerNumber() string {
	if m != nil {
		return m.CustomerNumber
	}
	return ""
}

func (m *DataRequest) GetThingName() string {
	if m != nil {
		return m.ThingName
	}
	return ""
}

func (m *DataRequest) GetThingDisplayName() string {
	if m != nil {
		return m.ThingDisplayName
	}
	return ""
}

func (m *DataRequest) GetThingSerial() string {
	if m != nil {
		return m.ThingSerial
	}
	return ""
}

func (m *DataRequest) GetPropertyName() string {
	if m != nil {
		return m.PropertyName
	}
	return ""
}

func (m *DataRequest) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *DataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DataRequest) GetPropertyId() int32 {
	if m != nil {
		return m.PropertyId
	}
	return 0
}

func (m *DataRequest) GetThingId() int32 {
	if m != nil {
		return m.ThingId
	}
	return 0
}

func (m *DataRequest) GetAlerts() []*AlertData {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *DataRequest) GetTemplateId() int32 {
	if m != nil {
		return m.TemplateId
	}
	return 0
}

func (m *DataRequest) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

type AlertData struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SettingValue         string     `protobuf:"bytes,3,opt,name=settingValue,proto3" json:"settingValue,omitempty"`
	AlertModule          string     `protobuf:"bytes,4,opt,name=alertModule,proto3" json:"alertModule,omitempty"`
	Status               int32      `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PriorityId           int32      `protobuf:"varint,6,opt,name=priorityId,proto3" json:"priorityId,omitempty"`
	Triggers             []*Trigger `protobuf:"bytes,7,rep,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AlertData) Reset()         { *m = AlertData{} }
func (m *AlertData) String() string { return proto.CompactTextString(m) }
func (*AlertData) ProtoMessage()    {}
func (*AlertData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{6}
}

func (m *AlertData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertData.Unmarshal(m, b)
}
func (m *AlertData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertData.Marshal(b, m, deterministic)
}
func (m *AlertData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertData.Merge(m, src)
}
func (m *AlertData) XXX_Size() int {
	return xxx_messageInfo_AlertData.Size(m)
}
func (m *AlertData) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertData.DiscardUnknown(m)
}

var xxx_messageInfo_AlertData proto.InternalMessageInfo

func (m *AlertData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlertData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AlertData) GetSettingValue() string {
	if m != nil {
		return m.SettingValue
	}
	return ""
}

func (m *AlertData) GetAlertModule() string {
	if m != nil {
		return m.AlertModule
	}
	return ""
}

func (m *AlertData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AlertData) GetPriorityId() int32 {
	if m != nil {
		return m.PriorityId
	}
	return 0
}

func (m *AlertData) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Trigger struct {
	Micro                string   `protobuf:"bytes,1,opt,name=micro,proto3" json:"micro,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Params               string   `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{7}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetMicro() string {
	if m != nil {
		return m.Micro
	}
	return ""
}

func (m *Trigger) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Trigger) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Trigger) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *Trigger) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DataResponse struct {
	//repeated Content listContent = 1;
	StatusCode           int64    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef68a669080b18c5, []int{8}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "EmptyRequest")
	proto.RegisterType((*ThingRequest)(nil), "ThingRequest")
	proto.RegisterType((*ThingResponse)(nil), "ThingResponse")
	proto.RegisterType((*PropertyResponse)(nil), "PropertyResponse")
	proto.RegisterType((*Template)(nil), "Template")
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*AlertData)(nil), "AlertData")
	proto.RegisterType((*Trigger)(nil), "Trigger")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
}

func init() { proto.RegisterFile("iot/message.proto", fileDescriptor_ef68a669080b18c5) }

var fileDescriptor_ef68a669080b18c5 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x8d, 0xe2, 0xf8, 0x36, 0x76, 0xbc, 0x0e, 0xb1, 0x58, 0x08, 0xde, 0xc0, 0x30, 0x84, 0x6c,
	0x60, 0x6c, 0x11, 0x1a, 0x4d, 0x2f, 0x4f, 0x7d, 0x29, 0x92, 0xd4, 0x30, 0xd0, 0x04, 0x85, 0x62,
	0xf4, 0x9d, 0xb6, 0x58, 0x45, 0x80, 0x24, 0xaa, 0x24, 0x95, 0xd4, 0x1f, 0xd0, 0x8f, 0xe8, 0x97,
	0xf4, 0xa1, 0x5f, 0xd2, 0xbf, 0x29, 0x78, 0x91, 0xcc, 0x24, 0x05, 0xd2, 0x37, 0x9e, 0x33, 0xa3,
	0x23, 0xce, 0x99, 0xe1, 0xc0, 0x41, 0xc2, 0xe4, 0x2c, 0xa3, 0x42, 0x90, 0x98, 0xe2, 0x82, 0x33,
	0xc9, 0x46, 0x27, 0x71, 0x22, 0x6f, 0xca, 0x15, 0x5e, 0xb3, 0x6c, 0x96, 0x25, 0x6b, 0xce, 0x66,
	0x31, 0x3b, 0x31, 0x07, 0x52, 0x24, 0x33, 0x9d, 0xa4, 0x4e, 0x36, 0x7d, 0x1c, 0x33, 0x16, 0xa7,
	0xd4, 0xf0, 0xab, 0xf2, 0xd3, 0xec, 0x8e, 0x93, 0xa2, 0xa0, 0x5c, 0x98, 0x78, 0x30, 0x80, 0xfe,
	0x45, 0x56, 0xc8, 0x4d, 0x48, 0x3f, 0x97, 0x54, 0xc8, 0xe0, 0x18, 0xfa, 0xcb, 0x9b, 0x24, 0x8f,
	0x2d, 0x46, 0xff, 0x40, 0x4b, 0x50, 0x9e, 0x90, 0xd4, 0xf7, 0x26, 0xde, 0xb4, 0x1b, 0x5a, 0x14,
	0x7c, 0xf7, 0x60, 0xdf, 0x26, 0x8a, 0x82, 0xe5, 0x82, 0xa2, 0x09, 0xf4, 0xa2, 0x44, 0x14, 0x29,
	0xd9, 0x5c, 0x91, 0x8c, 0xda, 0x74, 0x97, 0x72, 0xb4, 0x76, 0x5d, 0x2d, 0xf4, 0x1c, 0xa0, 0xe0,
	0xac, 0xa0, 0x5c, 0x26, 0x54, 0xf8, 0x8d, 0x49, 0x63, 0xda, 0x3b, 0x3d, 0xc0, 0x1f, 0x0c, 0xb5,
	0xa9, 0x7e, 0x10, 0x3a, 0x49, 0x08, 0xc1, 0x5e, 0xae, 0xfe, 0xb2, 0xa7, 0x85, 0xf4, 0x19, 0xfd,
	0x07, 0x1d, 0x49, 0xb3, 0x22, 0x25, 0x92, 0xfa, 0xcd, 0x89, 0x37, 0xed, 0x9d, 0x76, 0xf1, 0xd2,
	0x12, 0x61, 0x1d, 0x0a, 0xde, 0xc0, 0xf0, 0xa1, 0x74, 0x2d, 0xe7, 0x39, 0x72, 0x7f, 0x43, 0xf3,
	0x96, 0xa4, 0x25, 0xb5, 0x97, 0x35, 0x20, 0x18, 0x43, 0xa7, 0xd2, 0xfc, 0xdd, 0x57, 0xc1, 0xb7,
	0x06, 0xf4, 0xce, 0x89, 0x24, 0x95, 0x7f, 0xc7, 0x30, 0x58, 0x97, 0x42, 0xb2, 0x8c, 0xf2, 0xab,
	0x32, 0x5b, 0x51, 0x6e, 0xb3, 0x1f, 0xb0, 0xe8, 0x10, 0xba, 0x52, 0xd9, 0xa9, 0xbd, 0x33, 0x7f,
	0xdc, 0x12, 0xe8, 0x7f, 0x18, 0x6a, 0x70, 0xee, 0x18, 0xdc, 0xd0, 0x49, 0x8f, 0x78, 0xd5, 0x07,
	0xcd, 0x5d, 0x1b, 0xab, 0x8d, 0x43, 0x2e, 0x85, 0x02, 0xe8, 0x5b, 0x2b, 0x8d, 0x52, 0x53, 0xa7,
	0xdc, 0xe3, 0xd0, 0x08, 0x3a, 0x11, 0x91, 0x64, 0xb9, 0x29, 0xa8, 0xdf, 0x9a, 0x78, 0xd3, 0x66,
	0x58, 0xe3, 0xad, 0x33, 0x6d, 0xc7, 0x19, 0x34, 0xae, 0xbb, 0xb8, 0x59, 0x44, 0x7e, 0x47, 0x7f,
	0xe3, 0x30, 0xc8, 0x87, 0xb6, 0xbe, 0xc4, 0x22, 0xf2, 0xbb, 0x3a, 0x58, 0x41, 0x14, 0x40, 0x8b,
	0xa4, 0x94, 0x4b, 0xe1, 0x83, 0xee, 0x3d, 0xe0, 0xb7, 0x0a, 0x6a, 0x1b, 0x6d, 0x44, 0xa9, 0x57,
	0x1d, 0x5c, 0x44, 0x7e, 0xcf, 0xa8, 0x6f, 0x19, 0x55, 0x53, 0x85, 0x74, 0x4d, 0x7d, 0x53, 0x93,
	0xcb, 0x05, 0x3f, 0x3d, 0xe8, 0xd6, 0xca, 0x7f, 0xde, 0x73, 0xa5, 0x2d, 0xa8, 0x94, 0x49, 0x1e,
	0x7f, 0xd4, 0x41, 0xe3, 0xfc, 0x3d, 0x4e, 0xb9, 0xae, 0x6f, 0x7a, 0xc9, 0xa2, 0x32, 0xad, 0xe6,
	0xd2, 0xa5, 0xf4, 0xf4, 0x4b, 0x22, 0x4b, 0xa1, 0xfd, 0x6e, 0x86, 0x16, 0x19, 0xdf, 0x12, 0xc6,
	0x13, 0xed, 0x5b, 0xab, 0xf2, 0xad, 0x62, 0xd0, 0x11, 0x74, 0x24, 0x4f, 0xe2, 0x98, 0x72, 0xe1,
	0xb7, 0xb5, 0x3f, 0x1d, 0xbc, 0x34, 0x44, 0x58, 0x47, 0x82, 0xaf, 0x1e, 0xb4, 0x2d, 0xab, 0xaa,
	0xd0, 0x0b, 0xc1, 0x96, 0x66, 0x80, 0xea, 0x28, 0xcd, 0xa3, 0x82, 0x25, 0xb9, 0xb4, 0xe5, 0xd5,
	0x58, 0x79, 0xb1, 0x62, 0xd1, 0xc6, 0x56, 0xa6, 0xcf, 0xea, 0xbe, 0x05, 0xe1, 0x24, 0x13, 0xb6,
	0x18, 0x8b, 0xd4, 0xa4, 0x2a, 0xaf, 0x44, 0x41, 0xd6, 0xd5, 0xe8, 0x6c, 0x89, 0x00, 0x43, 0xdf,
	0x8c, 0xbf, 0x7d, 0x59, 0x63, 0x00, 0x53, 0xe7, 0x19, 0x8b, 0x8c, 0xd7, 0x8d, 0xd0, 0x61, 0x4e,
	0x7f, 0xec, 0x42, 0x6b, 0xc1, 0xe4, 0xf5, 0xed, 0x1a, 0x9d, 0x00, 0xcc, 0xa9, 0x9c, 0x13, 0x49,
	0xef, 0xc8, 0x06, 0xed, 0x63, 0x77, 0x0f, 0x8d, 0x06, 0xf8, 0xde, 0xb6, 0x09, 0x76, 0xd0, 0x33,
	0xe8, 0xcc, 0xa9, 0xd4, 0xec, 0xd3, 0xc9, 0x33, 0x18, 0x5c, 0x7c, 0x59, 0x97, 0x92, 0xd6, 0x8f,
	0xb7, 0x8f, 0x9d, 0x67, 0x3a, 0xda, 0xc7, 0xee, 0xad, 0x83, 0x1d, 0x74, 0x04, 0x8d, 0xf7, 0x2c,
	0x7e, 0x2a, 0xeb, 0x15, 0x0c, 0xe7, 0x54, 0x9e, 0xd3, 0xdb, 0x64, 0x4d, 0x2f, 0x49, 0xf1, 0x8e,
	0x24, 0x29, 0xfa, 0x0b, 0xc7, 0x0c, 0xab, 0x05, 0x5c, 0x7d, 0x35, 0xdc, 0x12, 0xd6, 0x94, 0x39,
	0xc0, 0x19, 0x2b, 0x73, 0x7b, 0xf9, 0x43, 0x6c, 0x76, 0x34, 0xae, 0x76, 0x34, 0xbe, 0x96, 0xbc,
	0x1a, 0xac, 0xd1, 0xbf, 0x8f, 0xa2, 0x8b, 0x5c, 0xbe, 0x7e, 0xa9, 0x83, 0xab, 0x96, 0x26, 0x5f,
	0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xaa, 0xde, 0x74, 0x28, 0x06, 0x00, 0x00,
}
